def includeme(config):
    config.add_route('home', '/')
    config.add_route('register', '/users/register')
    config.add_route('login', '/users/login')
    config.add_route('view_users', '/users/view_users')
    config.add_route('view_users_by_id', '/users/{id}')
    config.add_route('update_users','/update/users/{id}')
    config.add_route('delete_users','/delete/users/{id}')
    config.add_route('view_books', '/books/view_books')
    config.add_route('add_books', '/books/add_books')
    config.add_route('view_books_by_id', '/books/{id}')
    config.add_route('update_books','/update/books/{id}')
    config.add_route('delete_books','/delete/books/{id}')
    config.add_route('create_roles', '/roles')
    config.add_route('view_roles', '/roles/view_roles')
    config.add_route('create_users_roles', '/users_roles')
    config.add_route('view_users_roles', '/roles/view_users_roles')
    config.scan()